languages: go
sudo: false

go:
  - 1.x
  - master

env:
  - GO111MODULE=on

go_import_path: github.com/dgellow/lit

script:
  - go get -u -t
  - go vet ./...
  - go test -v -race ./...
  - go build ./...
